### PR TITLE
Add Network Overview page for Ethereum

### PR DESCRIPTION
**Pull request by pyr0gan**
- Draft a page for Ethereum below **Network Data** > **Network Overview**, documenting the Network Overview API.

Screenshot 2023-06-13 at 10 14 39 AM

### CODE REVIEW

**Comment by guillaumegaluz** [comment]
- remove bullet point for "None"
- remove "To query this..."
- change "Estimate Ethereum Activation & Exit Queue" to "Network Overview" everywhere
- remove "For Ethereum validators and 3 bullet points"
- @coltonc3 can you update the copy for:
Screenshot 2023-06-12 at 17 27 12

**Comment by coltonc3** [comment]
> * remove bullet point for "None"
> * remove "To query this..."
> * change "Estimate Ethereum Activation & Exit Queue" to "Network Overview" everywhere
> * remove "For Ethereum validators and 3 bullet points"
> * @coltonc3 can you update the copy for:
> 
> Screenshot 2023-06-12 at 17 27 12

@guillaumegaluz when you say "the copy" do you mean our notion doc?

**Comment by pyr0gan** [comment]
> * remove bullet point for "None"
 
Noting that this makes it inconsistent with other GET requests on the docs that do not have request parameters. [Example - ETH Aggregated Unstaking](https://docs.figment.io/staking/ethereum/aggregated-unstaking/#get-aggregated-unstaking-flow-status).

> * remove "To query this..."

- What should the description be changed to? The component uses the first line of the content as the description, so removing the description breaks the display:

Screenshot 2023-06-13 at 8 14 27 AM

- With a description line, the display is correct:

Screenshot 2023-06-13 at 8 32 51 AM


> * change "Estimate Ethereum Activation & Exit Queue" to "Network Overview" everywhere

✅ 

> * remove "For Ethereum validators and 3 bullet points"

✅ 

---

@coltonc3 Please provide the description (copy):

_Description_

`activation_estimate` : `object`
  `hours` : `number` _Description_

`exit_estimate` : `object`
  `hours` : `number` _Description_

`withdrawal_estimate` : `object`
  `hours_min` : `number` _Description_
  `hours_max` : `number` _Description_

**Comment by guillaumegaluz** [comment]
- Request. i mean just remove the bullet point. Keep "None". Bullet points only make sense if there's a list
- Just remove the description and leave the Response after the URL
- @coltonc3 can you update the description for fields?

**Pull request merged**
