### PR TITLE
Add Signatures page

### PR DESCRIPTION
**Pull request by pyr0gan**
- Add a **Signatures** page to the sidebar, below **Errors**
  - Re-numbered the sidebar positions to keep everything in place
Screenshot 2023-05-09 at 4 31 31 PM
Screenshot 2023-05-09 at 4 31 35 PM

Edit: updated screenshots

### CODE REVIEW

**Comment by guillaumegaluz** [comment]
- @pyr0gan Remove the list of endpoints in first line
- @pyr0gan Drop the two column layout for this
- @avanderbeek can you give us a one line sentence at the very top for what this is about? "To authenticate response to calls providing... Figment uses....". A rehash of the customer need

**Comment by pyr0gan** [comment]
@guillaumegaluz 

Screenshot 2023-05-09 at 1 40 20 PM
Screenshot 2023-05-09 at 1 40 24 PM

**Comment by guillaumegaluz** [comment]
- @pyr0gan Remove the list of endpoints in first line 🔴 
- @pyr0gan Drop the two column layout for this ✅ 
- @pyr0gan "This can be aquired..." has bullet points that are not formatted 🔴 
- @avanderbeek can you give us a one line sentence at the very top for what this is about? "To authenticate response to calls providing... Figment uses....". A rehash of the customer need 🔴

**Comment by pyr0gan** [comment]
> * @pyr0gan Remove the list of endpoints in first line 🔴 <- @guillaumegaluz see commit e944ec6 
> * @pyr0gan Drop the two column layout for this ✅
> * @pyr0gan "This can be aquired..." has bullet points that are not formatted 🔴 <- @guillaumegaluz see commit 9a12814 
> * @avanderbeek can you give us a one line sentence at the very top for what this is about? "To authenticate response to calls providing... Figment uses....". A rehash of the customer need 🔴

Screenshot 2023-05-09 at 3 52 04 PM

**Comment by guillaumegaluz** [comment]
in your previous message you posted screenshots that show differently.

best practice: don't post screenshots with comments and instead only keep some in the PR description + update them as you make changes.

**Comment by guillaumegaluz** [comment]
Once you've updated the PR desc with the latest screenshots i can review again! Thanks

**Comment by pyr0gan** [comment]
> Once you've updated the PR desc with the latest screenshots i can review again! Thanks

Screenshots updated

**Comment by avanderbeek** [comment]
It's late so check me on this one: 

"When sending responses which provide validator metadata, Figment includes a cryptographic signature allowing you to confirm that the validator pub key originates from Figment’s secure provisioning infrastructure."

**Comment by pyr0gan** [comment]
@avanderbeek Looks good in place:

Screenshot 2023-05-10 at 8 18 25 AM

**Review by guillaumegaluz — APPROVED** [review]
lgtm

**Pull request merged**
