### PR TITLE
add guides for solana split stake acct flow

### PR DESCRIPTION
**Pull request by dvanderbeek**
Adding docs for the Solana split stake account flow. LMK if I did anything wrong here, I'm still getting familiar with these docs

### CODE REVIEW

**Comment by yash-sharma1** [comment]
Hey, @dvanderbeek Thanks for submitting the PR, this is great.
I was actually working on this here - https://github.com/figment-networks/figment-documentation/tree/ys/split-stake-guides but was on hold as I wasn't having responses ready. I'll follow this PR to get the request & responses and will submit a PR.
We'll merge the PR in the `development` branch instead of `main` first. Split stake docs will be live in docs soon.

**Comment by dvanderbeek** [comment]
> Hey, @dvanderbeek Thanks for submitting the PR, this is great.
> I was actually working on this here - https://github.com/figment-networks/figment-documentation/tree/ys/split-stake-guides but was on hold as I wasn't having responses ready. I'll follow this PR to get the request & responses and will submit a PR.
> We'll merge the PR in the `development` branch instead of `main` first. Split stake docs will be live in docs soon.

Sounds good. Quick note - all the data in the examples here are just copied over from the transfer flow. I didn’t have accounts set up to actually run through the flow myself

**Comment by yash-sharma1** [comment]
> > Hey, @dvanderbeek Thanks for submitting the PR, this is great.
> > I was actually working on this here - https://github.com/figment-networks/figment-documentation/tree/ys/split-stake-guides but was on hold as I wasn't having responses ready. I'll follow this PR to get the request & responses and will submit a PR.
> > We'll merge the PR in the `development` branch instead of `main` first. Split stake docs will be live in docs soon.
> 
> Sounds good. Quick note - all the data in the examples here are just copied over from the transfer flow. I didn’t have accounts set up to actually run through the flow myself

Noted, Thanks. I've staked some extra tokens on testnet which will be fully delegated today, I'll try to get the actual responses.

**Comment by yash-sharma1** [comment]
Closing this PR with ref to PR #205

**Pull request closed without merging**
